inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Style/AsciiComments:
  Exclude:
    - 'termapp/core_ext/string.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/ClassLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'test/test_helper.rb'

Style/Encoding:
  Enabled: true

Style/IndentHash:
  EnforcedStyle: consistent

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MethodLength:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable
