inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Style/AsciiComments:
  Exclude:
    - 'termapp/core_ext/string.rb'
    - 'spec/termapp/core_ext/string_spec.rb'
