inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Style/AsciiComments:
  Exclude:
    - 'termapp/core_ext/string.rb'

Style/ClassLength:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/IndentHash:
  EnforcedStyle: consistent

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MethodLength:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable
